name: Build SpaceWarp++

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions: write-all

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo rustc --release -- -Clink-args="/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup"

    - name: Move assets
      run: move "assets" "./target/release"

    - name: Move level (1)
      run: move level_1.sw "./target/release"

    - name: Move level (2)
      run: move level_2.sw "./target/release"

    - name: Move level (3)
      run: move level_3.sw "./target/release"

    - name: Move level (4)
      run: move level_4.sw "./target/release"

    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ./target/release/
