name: Build SpaceWarp++

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions: write-all

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Setup
      run: rustup target add x86_64-pc-windows-gnu

    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu

    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ./target/x86_64-pc-windows-gnu
